// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spellen.API.Data;

namespace Spellen.API.Migrations
{
    [DbContext(typeof(SpellenContext))]
    [Migration("20210428174212_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategorieSpel", b =>
                {
                    b.Property<Guid>("CategorieenCategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpellenSpelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategorieenCategorieId", "SpellenSpelId");

                    b.HasIndex("SpellenSpelId");

                    b.ToTable("CategorieSpel");
                });

            modelBuilder.Entity("MateriaalSpel", b =>
                {
                    b.Property<Guid>("MateriaalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpellenSpelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MateriaalId", "SpellenSpelId");

                    b.HasIndex("SpellenSpelId");

                    b.ToTable("MateriaalSpel");
                });

            modelBuilder.Entity("Spellen.API.Models.Categorie", b =>
                {
                    b.Property<Guid>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categorieen");

                    b.HasData(
                        new
                        {
                            CategorieId = new Guid("92c8e6ca-d4c9-4d30-9566-dd1d0ec7f08f"),
                            Naam = "Pleinspelen"
                        },
                        new
                        {
                            CategorieId = new Guid("761846ce-2682-4ca4-a166-06731d5e491f"),
                            Naam = "Verstoppen"
                        });
                });

            modelBuilder.Entity("Spellen.API.Models.Materiaal", b =>
                {
                    b.Property<Guid>("MateriaalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MateriaalId");

                    b.ToTable("Materiaal");

                    b.HasData(
                        new
                        {
                            MateriaalId = new Guid("78d6af00-655e-48f2-ad2e-5ba2cb5534fd"),
                            Item = "Potjes"
                        });
                });

            modelBuilder.Entity("Spellen.API.Models.Spel", b =>
                {
                    b.Property<Guid>("SpelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leeftijd_tot")
                        .HasColumnType("int");

                    b.Property<int>("Leeftijd_vanaf")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spelers_max")
                        .HasColumnType("int");

                    b.Property<int>("Spelers_min")
                        .HasColumnType("int");

                    b.Property<string>("Terrein")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uitleg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpelId");

                    b.ToTable("Spellen");

                    b.HasData(
                        new
                        {
                            SpelId = new Guid("eb0c83ff-9cb0-424d-9cc3-579d2b40e466"),
                            Duur = "15 tot 30 minuten",
                            Leeftijd_tot = 99,
                            Leeftijd_vanaf = 5,
                            Naam = "Tussen 2 vuren",
                            Spelers_max = 99,
                            Spelers_min = 6,
                            Terrein = "Buiten,Grote zaal",
                            Uitleg = "Tussen 2 vuren is een spel met twee teams en een bal en je gooit de andere eraan. En O ja, er is ook iets met een kapitein."
                        },
                        new
                        {
                            SpelId = new Guid("4cc8e6a7-b6d6-42d3-8995-36cace9b29b0"),
                            Duur = "5 tot 20 minuten",
                            Leeftijd_tot = 99,
                            Leeftijd_vanaf = 5,
                            Naam = "Kiekeboe",
                            Spelers_max = 99,
                            Spelers_min = 3,
                            Terrein = "Buiten",
                            Uitleg = "Kiekeboe is een verstopspel. Er is één zoeker die begint af te tellen vanaf 20. Binnen deze tijd moet iedereen zich verstopt hebben. De zoeker mag 3 stappen zetten en dan 'Kiekeboe' roepen, hij begint dan af te tellen vanaf 19, iedereen moet hem dan in die tijd aantikken en zich terug verstoppen... Wanneer je gevonden bent, mag je niet terug verstoppen."
                        });
                });

            modelBuilder.Entity("CategorieSpel", b =>
                {
                    b.HasOne("Spellen.API.Models.Categorie", null)
                        .WithMany()
                        .HasForeignKey("CategorieenCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spellen.API.Models.Spel", null)
                        .WithMany()
                        .HasForeignKey("SpellenSpelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MateriaalSpel", b =>
                {
                    b.HasOne("Spellen.API.Models.Materiaal", null)
                        .WithMany()
                        .HasForeignKey("MateriaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spellen.API.Models.Spel", null)
                        .WithMany()
                        .HasForeignKey("SpellenSpelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
